### ISSUE TITLE
Unable to lauche application (exit with code 0xc000007b)

### ISSUE THREAD

**Issue by UrielTallon** [3omdawy/MPC-Quiz#1]
Is it possible to give an explanation on how you get there? I tried to use your libraries and DLLs in my project. It compiles but I am unable to launch the application as it exists immediately with code 0xc000007b. I tried to look what it means and apparently the most probable cause is trying to build a project for x86 platform while using dll and/or libraries compiled for x64 platforms (or vice-versa). My Visual Studio builds by default for x86 platform, I tried to build for x64 but it doesn't solve anything (it makes things worse actually).

I am working on windows 7 professional with Visual Studio 2015 community edition. I have included the python27.lib from my local python 27 installation and the IpOpt.lib, IpOptFSS.lib, IpOptFSS.dll, Ipopt-vc10.dll, Ipopt-vc10.lib from the build directory of your repo cloned locally (apparently, only those are required for the compilation to succeed).

If it's necessary I would rebuild the libraries and dll locally but I don't have any idea on how to do it.

Thank you in advance,

**Comment by 3omdawy** [comment]
I can't remember the actual steps but roughly I downloaded CppAd and IpOpt files, built them (especially CppAd to add configure.hpp) and added them to the project. Refer to the instructions using Docker in the project readme.

Then it was a matter of finding online the dlls that corrected linking errors (mainly IpOpt and mcvsr100)
The part of linking with Python in matplotlib did not work with me so I commented it out, but otherwise it build and works with VS2017 (verified values using debugging).

Note: Ipopt files (dlls, lib ...) are for Windows 10 64-bit.
If you have a 32-bit operating system may be you should search for IpOpt dlls for 32-bit systems.

bad_alloc exception is related to msvcp100.dll, msvcr100.dll , and msvcr100d.dll.
Do you include them in your directory? May be you need to include the right dlls if your system is different fro mine.

Note: I also needed to comment the line containing Integer print_level and max_cpu_time

**Comment by UrielTallon** [comment]
Thank you for your suggestion. So I downloaded the dll from https://www.coin-or.org/download/binary/Ipopt/; the zip archive has 2 subdirectories for 32-bit and 64-bit platforms. I included the IpOptFSS.lib/dll and IpOpt-vc10.lib/dll from the win32 subdirectory and try to recompile. Compilation is OK but the application still crashes after being launch with the same error as previously mentioned.

Afterwards, I included EVERYTHING in the win32 subdirectory, recompile and, surprise, application launches without any (apparent) issue. After fiddling with the dlls here and there, I found that the required dlls are:

* IpOptFSS.dll

* IpOpt-vc10.dll

* libiomp5md.dll

Without the last one, the application just crash... Strange. It seems to work now.

Thanks again for the help.
